[env:receiver]
platform = espressif8266
board = d1_wroom_02
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8
    olikraus/U8g2@^2.36.5
    IRremoteESP8266
build_src_filter = +<main_reciever.cpp> -<main_transmiter.cpp>

[env:transmitter]
platform = espressif8266
board = d1_wroom_02
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8
    IRremoteESP8266
build_src_filter = +<main_transmiter.cpp> -<main_reciever.cpp>
